version: '3.8'

services:
  # Kafka en modo KRaft (sin Zookeeper)
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv==
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - kafka-net

  # Kafdrop (visualizador Kafka)
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-net
    restart: always

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - kafka
    networks:
      - kafka-net
    ports:
      - "3000:3000"
    restart: always

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    depends_on:
      - kafka
    networks:
      - kafka-net
    restart: always

  # User Service
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - kafka
    networks:
      - kafka-net
    restart: always

  # Log Service
  log-service:
    build:
      context: ./log-service
    container_name: log-service
    depends_on:
      - kafka
    networks:
      - kafka-net
    restart: always

volumes:
  kafka-data:

networks:
  kafka-net:
